theme: minima
title: bolggers
author: pushpraj jaiswal
email: pushprajapp12@gmail.com.com
description: > hey friends how are you today i am starting the git hub pages and learn about the github b pages soncan you helo me to learn the github . lastly i am build the personal portpolio website

# social links
twitter_username: @pusjprajjaiswa# DO NOT include the @ character, or else the build will fail!
github_username: puahprajjaiswal # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
